version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://github.com/xpack-dev-tools/qemu-arm-xpack/releases/download/v2.8.0-10/xpack-qemu-arm-2.8.0-10-win32-x64.zip

build_script:
- cmd: echo %URL%
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
