version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://github.com/openssl/openssl/archive/OpenSSL_1_1_1c.zip

build_script:
- cmd: echo %URL%
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
