version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://github.com/svaarala/duktape-releases/archive/v2.3.0.tar.gz

build_script:
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
